[tool.poetry]
name = "dslr"
version = "0.1.0"
description = ""
authors = ["mpochard"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.6"
pandas = "^2.2.2"
matplotlib = "^3.9.0"
ruff = "^0.4.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
